### ISSUE TITLE
nodename nor servname provided, or not known (sts.us.amazonaws.com:443)

### ISSUE THREAD

**Issue by phillijw** [abuzuhri/Amazon-SP-API-CSharp#273]
This is my first time using the code so I'm not sure if I'm doing it right but when I am trying to connect and then list catalog items, I am getting this error which seems to be a DNS problem or a misconfiguration using the wrong marketplace maybe.

```
ystem.Net.Http.HttpRequestException: nodename nor servname provided, or not known (sts.us.amazonaws.com:443)
 ---> System.Net.Sockets.SocketException (0xFFFDFFFF): nodename nor servname provided, or not known
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Amazon.Runtime.HttpWebRequestMessage.GetResponseAsync(CancellationToken cancellationToken)
   at Amazon.Runtime.Internal.HttpHandler`1.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.Unmarshaller.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.ErrorHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.ErrorHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.EndpointDiscoveryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.EndpointDiscoveryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CredentialsRetriever.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.ErrorCallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.MetricsHandler.InvokeAsync[T](IExecutionContext executionContext)
   at FikaAmazonAPI.Services.TokenGeneration.SignWithSTSKeysAndSecurityTokenAsync(IRestRequest restRequest, String host, AmazonCredential amazonCredential)
   at FikaAmazonAPI.Services.RequestService.ExecuteRequestTry[T](RateLimitType rateLimitType)
   at FikaAmazonAPI.Services.RequestService.ExecuteRequestAsync[T](RateLimitType rateLimitType)
   at FikaAmazonAPI.Services.CatalogItemService.ListCatalogItemsAsync(ParameterListCatalogItems parameterListCatalogItems)
   at SellerBot.Worker.Worker.ExecuteAsync(CancellationToken stoppingToken) in /Users/phillijw/repos/sellerbot/SellerBot.Worker/Worker.cs:line 40
```

The code I'm using looks like this:

```
                var creds = new AmazonCredential {
                    AccessKey = "AK......",
                    SecretKey = "nj.....",
                    //RoleArn = "arn:aws:iam::51431234567:role/MyRole",
                    RoleArn = "arn:aws:iam::51431234567:user/MyUser",
                    ClientId = "amzn1.application-oa2-client........",
                    ClientSecret = "b9......",
                    RefreshToken = "Atzr|Iw...........",
                    MarketPlace = FikaAmazonAPI.Utils.MarketPlace.US
                };
                var conn = new AmazonConnection(creds);

                var x = await conn.CatalogItem.ListCatalogItemsAsync(new ParameterListCatalogItems {
                    Query = "WAGO",                    
                });


```

**Comment by abuzuhri** [comment]
You are using AM USER instead of roles 

RoleArn = "arn:aws:iam::51431234567:

That not true .

**Comment by phillijw** [comment]
What should I be using instead? I'm brand new to AWS. I'm not aware of any other roles that aren't IAM...

**Comment by abuzuhri** [comment]
* RoleArn = "arn:aws:iam::51431234567:role/MyRole",*

This true and you need to be sour same role use in your developer application

**Comment by phillijw** [comment]
I have switched to using roles and I'm getting the same error.

**Comment by abuzuhri** [comment]
Is the same roles used in the application ?
Do you follow all step https://developer-docs.amazon.com/sp-api/docs/creating-and-configuring-iam-policies-and-entities ?

**Comment by abuzuhri** [comment]
Can you try use proxy or different network error seem server blocked  ...

**Comment by phillijw** [comment]
The code is trying to hit `sts.us.amazonaws.com` and that doesn't exist. I have tried to ping it from multiple locations and it doesn't resolve

**Comment by abuzuhri** [comment]
The error came from dependency ([AWSSDK.SQS](https://www.nuget.org/packages/AWSSDK.SQS/)) but i think its because of wrong configuration only , many use the library and no body face same error

**Comment by abuzuhri** [comment]
If you try to get order you face same error ?

**Comment by phillijw** [comment]
I just completely went through the instructions you linked to and re-setup the users, roles, etc. I also changed the code to call `conn.Orders.GetOrders` and I'm getting the same error. I have no idea what I'm doing wrong

**Comment by abuzuhri** [comment]
Send me private email will try to help you now

**Comment by abuzuhri** [comment]
dependency now updated please check again

**Comment by phillijw** [comment]
My aws profile (`~/.aws/config`) file had the region set to `US`. Once I changed it to `us-east-1` it started working. I'm not sure why it was set to `US` but that causes the code to override the default region of `us-east-1`

**Comment by abuzuhri** [comment]
Very strange Amazon not mention region setup in aws
