### ISSUE TITLE
Please provide a video how to set up Amazon AWS/IAM permissions for User ARNs

### ISSUE THREAD

**Issue by GuybrushX** [abuzuhri/Amazon-SP-API-CSharp#29]
I've created a sample/test PHP application with another library which is using the following approach for accessing Amazon SP API:
https://github.com/amzn/selling-partner-api-docs/issues/128

My sample is based on that library and was running fine with my credentials:
https://github.com/jlevers/selling-partner-api/

It failes with your library though.

AWS/IAM is pretty new to me but it seems that your library is using role based ARNs only and not user based ARNs. According to the issue discussed in my link user based is totally fine and easier to set up, too. At least the AmazonConnection classt takes "RoleArn" only and no "UserArn" -> I tried to specify my User ARN but it gave me the following error:
System.AggregateException
  HResult=0x80131500
  Message=One or more errors occurred. (User: arn:aws:iam::123456789:user/SP-API_User is not authorized to perform: sts:AssumeRole on resource: arn:aws:iam::123456789:user/SP-API_User)
  Source=System.Private.CoreLib
  StackTrace:
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at FikaAmazonAPI.Services.TokenGeneration.SignWithSTSKeysAndSecurityToken(IRestRequest restRequest, String host, AmazonCredential amazonCredential)
   at FikaAmazonAPI.Services.RequestService.ExecuteRequest[T]()
   at FikaAmazonAPI.Services.OrderService.GetOrder(ParameterGetOrder parameter)
   at ProfitCalc.MainWindow.Button_Click(Object sender, RoutedEventArgs e) in C:\Users\mg\OneDrive\Source\Repos\ProfitCalc\ProfitCalc\MainWindow.xaml.cs:line 57
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.UIElement.OnMouseLeftButtonUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.Run()
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run()
   at ProfitCalc.App.Main()

  This exception was originally thrown at this call stack:
    [External Code]

Inner Exception 1:
AmazonSecurityTokenServiceException: User: arn:aws:iam::123456789:user/SP-API_User is not authorized to perform: sts:AssumeRole on resource: arn:aws:iam::1234567890:user/SP-API_User

Inner Exception 2:
HttpErrorResponseException: Exception of type 'Amazon.Runtime.Internal.HttpErrorResponseException' was thrown.

I think I assigned that sts:AssumeRole already but it's still not working.

Hope that is clear and you can either implement it or provide a video/guide how to set up the role based/STS authentication properly.

**Comment by wheelersf** [comment]
abuzuhri's API requires a 'role' ARN...not a 'user' ARN on the application level.  Make sure you setup the AWS user credentials EXACTLY as they are specified in all 5 steps.

**Comment by abuzuhri** [comment]
@GuybrushX

Please follow all step Here 
https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/developer-guide/SellingPartnerApiDeveloperGuide.md

And message me if you still need help tareq.abuzuhri [@@] gmail.com


you need to fill Role ARN inside AmazonConnection parameter and same Role ARN fill it in amazon application when you create it , you need to be carefully and do all steps here exactly https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/developer-guide/SellingPartnerApiDeveloperGuide.md

**Comment by wheelersf** [comment]
Hi Tareq,
Thanks for sharing such an awesome API!
I'm new on GitHub and accidentally forked your API.  Can you tell me how I would delete/remove it?

Thanks,Scott    On Tuesday, December 14, 2021, 10:41:26 AM EST, Tareq Abuzuhri ***@***.***> wrote:  
 
 


@GuybrushX

Please follow all step Here
https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/developer-guide/SellingPartnerApiDeveloperGuide.md

And message me if you still need help tareq.abuzuhri [@@] gmail.com

you need to fill Role ARN inside AmazonConnection parameter and same Role ARN fill it in amazon application when you create it , you need to be carefully and do all steps here exactly https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/developer-guide/SellingPartnerApiDeveloperGuide.md

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by GuybrushX** [comment]
> abuzuhri's API requires a 'role' ARN...not a 'user' ARN on the application level. Make sure you setup the AWS user credentials EXACTLY as they are specified in all 5 steps.

Thanks for your reply. If you read my message again and also the links you'll see that I know that already but it was a question to add support for the User ARN since other frameworks support that, too :-)

I'll give it a try again with new credentials and see how it goes.

**Comment by GuybrushX** [comment]
> @GuybrushX
> 
> Please follow all step Here https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/developer-guide/SellingPartnerApiDeveloperGuide.md
> 
> And message me if you still need help tareq.abuzuhri [@@] gmail.com
> 
> you need to fill Role ARN inside AmazonConnection parameter and same Role ARN fill it in amazon application when you create it , you need to be carefully and do all steps here exactly https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/developer-guide/SellingPartnerApiDeveloperGuide.md

Thank you very much for your fast reply. I gave the Amazon docs another try and this time it is working! :-)

Only the PII part isn't working as you mentioned in your video... I think I don't need it yet but here is another PHP library which is pretty famous and feature rich and it automatically creates that RDT in the background when needed. Just as a reference (I mentioned it already but just in case you missed it):
https://github.com/jlevers/selling-partner-api/

Let's see if I can create what I need with it (profit calculation across different marketplaces with respect to different shipping costs and fees).

Thanks a lot for your work! :-)

**Comment by abuzuhri** [comment]
" automatically creates that RDT in the background when needed."

Do you try this future your self ?

**Comment by coder771** [comment]
I downloaded your API code and it looks amazing, can you please let me know how did you manage to have all the APIs(order,feed,shipping etc) json model to have generated client using swagger, I tried swagger editor and it just allows one file at a time, and can create 1 client library at a time

**Comment by guruksk** [comment]
https://github.com/abuzuhri/Amazon-SP-API-CSharp/issues/565

Amazon support team asking us to use the UserARN only for our 'App Client' in Developer Central page. So we are asked to skip Security Token Service (STS) api call during postman execution.
We generate LWA token and then directly call SP-Api, and everything working fine, able to call the reports api and get response.

Since Amazon support team itself mentioning to use UserARN in some case and also Amazon C# SDK also provide option to call the SP api's without using RoleARN
https://developer-docs.amazon.com/sp-api-blog/docs/automate-your-sp-api-calls-using-the-c-sdk

As per few discussion in issues/29 & issues/533, I can understand CSharpAmazonSpAPI will not work without RoleArn
1. Why CSharpAmazonSpAPI made mandatory to pass RoleArn?
2. Do we have any plans to support UserARN or allow to call SP-api without RoleArn?

Please provide your valuable answer. Advance thanks.
