### ISSUE TITLE
Null-ref exception in GetOrderItemsAsync

### ISSUE THREAD

**Issue by HakanL** [abuzuhri/Amazon-SP-API-CSharp#375]
I upgraded to Nuget version 1.5.5 and I'm starting to get an exception in GetOrderItemsAsync, here's the stack:
System.NullReferenceException: Object reference not set to an instance of an object.
   at FikaAmazonAPI.Services.RequestService.SaveLastRequestHeader(IReadOnlyCollection`1 parameters)
   at FikaAmazonAPI.Services.RequestService.ExecuteRequestTry[T](RateLimitType rateLimitType)
   at FikaAmazonAPI.Services.RequestService.ExecuteRequestAsync[T](RateLimitType rateLimitType)
   at FikaAmazonAPI.Services.OrderService.GetOrderItemsAsync(String orderId, IParameterBasedPII ParameterBasedPII)

**Comment by abuzuhri** [comment]
Can you share the  code you use , i want to generate same problem

**Comment by HakanL** [comment]
The code is just calling GetOrderItemsAsync with an order id. But it works most of the time, I've only received this exception once or twice, so maybe it was bad data coming in for an order.

**Comment by RenzoF** [comment]
weird one as the only way this could happen is if the response.headers is null, I have added a null check so this shouldn't happen anymore, please reopen if you still see it in the latest code
