### ISSUE TITLE
Using sandbox for the first time

### ISSUE THREAD

**Issue by ledjon-behluli** [abuzuhri/Amazon-SP-API-CSharp#434]
Great project, props on it!

I had a question, when I try to run the sandbox example (see below)

```cs
AmazonConnection amazonConnection = new AmazonConnection(new AmazonCredential()
{
     AccessKey = "AKIAXXXXXXXXXXXXXXX",
     SecretKey = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
     RoleArn = "arn:aws:iam::XXXXXXXXXXXXX:role/XXXXXXXXXXXX",
     ClientId = "amzn1.application-XXX-client.XXXXXXXXXXXXXXXXXXXXXXXXXXXX",
     ClientSecret = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
     RefreshToken= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
     MarketPlace = MarketPlace.UnitedKingdom,
     Environment=Environments.Sandbox
});

var orders = amazonConnection.Orders.GetOrders
(
     new FikaAmazonAPI.Parameter.Order.ParameterOrderList
     {
         TestCase = Constants.TestCase200
     }
);
```

I get an authentication error:

```
System.SystemException
  HResult=0x80131501
  Message=Error getting LWA Access Token
  Source=FikaAmazonAPI
  StackTrace:
   at FikaAmazonAPI.AmazonSpApiSDK.Runtime.LWAClient.<GetAccessTokenAsync>d__15.MoveNext() in C:\Users\behlu\Desktop\test\Amazon-SP-API-CSharp-main\Source\FikaAmazonAPI\AmazonSpApiSDK\Runtime\LWAClient.cs:line 60
   at FikaAmazonAPI.Services.TokenGeneration.<RefreshAccessTokenAsync>d__0.MoveNext() in C:\Users\behlu\Desktop\test\Amazon-SP-API-CSharp-main\Source\FikaAmazonAPI\Services\TokenGeneration.cs:line 36
   at FikaAmazonAPI.Services.RequestService.<RefreshTokenAsync>d__51.MoveNext() in C:\Users\behlu\Desktop\test\Amazon-SP-API-CSharp-main\Source\FikaAmazonAPI\Services\RequestService.cs:line 364
   at FikaAmazonAPI.Services.RequestService.<CreateAuthorizedRequestAsync>d__36.MoveNext() in C:\Users\behlu\Desktop\test\Amazon-SP-API-CSharp-main\Source\FikaAmazonAPI\Services\RequestService.cs:line 70
   at FikaAmazonAPI.Services.OrderService.<GetOrdersAsync>d__2.MoveNext() in C:\Users\behlu\Desktop\test\Amazon-SP-API-CSharp-main\Source\FikaAmazonAPI\Services\OrderService.cs:line 49
   at FikaAmazonAPI.Services.OrderService.GetOrders(ParameterOrderList searchOrderList) in C:\Users\behlu\Desktop\test\Amazon-SP-API-CSharp-main\Source\FikaAmazonAPI\Services\OrderService.cs:line 20
   at Program.<<Main>$>d__0.MoveNext() in C:\Users\behlu\Desktop\test\ConsoleApp1\ConsoleApp1\Program.cs:line 82
   at Program.<Main>(String[] args)

Inner Exception 1:
IOException: Unsuccessful LWA token exchange

Inner Exception 2:
HttpRequestException: Request failed with status code Unauthorized
```

The example on the readme doesn't include the marketplace, but without it an NullReferenceException is thrown.

1. Do you have any idea how to fix this?
2. Can I also test the Shipping API via sandbox?

Thanks

**Comment by abuzuhri** [comment]
"`Unsuccessful LWA token exchange`" this error mean you don't follow the true step to generate refresh token 

As I remember all API ready with **sandbox**

for marketplace we automatically add current marketplace if you don't include , if there is bug please open issue and we will solve it

**Comment by ledjon-behluli** [comment]
Yes there is a bug with marketplace and sandbox (i'll open an issue or PR later).

But can you answer this for me: for sandbox, do I need an actual token, keys, secretes ..., or can I use these XXXX values that are in the examples?

**Comment by abuzuhri** [comment]
You need read token and key ...

**Comment by ledjon-behluli** [comment]
Appreciated, thank you!

Btw, here is the issue with the missing marketplace: https://github.com/abuzuhri/Amazon-SP-API-CSharp/issues/435
