### ISSUE TITLE
Error while submitting POST_FLAT_FILE_PRICEANDQUANTITYONLY_UPDATE_DATA

### ISSUE THREAD

**Issue by Tajanos** [abuzuhri/Amazon-SP-API-CSharp#447]
I get this in version 1.5.26.0:

Invalid URI: The Uri string is too long.

Stack trace:

   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
   at FikaAmazonAPI.Services.FeedService.<PostFileDataAsync>d__22.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FikaAmazonAPI.Services.FeedService.<SubmitFeedAsync>d__20.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FikaAmazonAPI.Services.FeedService.SubmitFeed(String XmlContentOrFilePath, FeedType feedType, List`1 marketPlaceIds, FeedOptions feedOptions, ContentType contentType)

My code:

            var Connection = GetAmazonConnection(Credentials);

            var FeedId = Connection.Feed.SubmitFeed(Data, Constants.FeedType.POST_FLAT_FILE_PRICEANDQUANTITYONLY_UPDATE_DATA, new List<string>() { Credentials.MarketPlaceId }, null, Constants.ContentType.TXT);

**Comment by RenzoF** [comment]
what are you passing in Data, a path to the flat file or the string contents?
either way, can you try the other way as well to see if it works?

**Comment by JowJoris** [comment]
It's because in PR #441 introduces a check to check if the parameter `contentOrFilePath` is a file.
If you put XML into the new Uri() constructor it breaks.

**Comment by smithburger** [comment]
What string are you trying to pass?

**Comment by Tajanos** [comment]
I am passing a tab-delimited string that looks like this:

sku	price	quantity	handling-time
SKU1	59.38	7	5
SKU2	58.64	19	5
SKU3	58.64	19	5

Since the method allows either TXT or XML for the content and the variable is called string XmlContentOrFilePath, I'd expect that the TXT content would be handled as well.

I could also pass a file path but, just so you know, right now I save my file to a UNC path with \\ in front of the path.

**Comment by abuzuhri** [comment]
@JowJoris @Tajanos @smithburger Now version 1.5.27 ready for test this issue
Thanks @RenzoF for patch to solve it

**Comment by abuzuhri** [comment]
please use this will solve the problem
`
var feedID = amazonConnection.Feed.SubmitFeedContent(xml, FeedType.POST_PRODUCT_DATA);
`

or

`
var feedID = amazonConnection.Feed.SubmitFeedFile(path, FeedType.POST_PRODUCT_DATA);
`
