### ISSUE TITLE
Serialization Error on FulFillmentInbound.GetTransportDetails

### ISSUE THREAD

**Issue by youst03** [abuzuhri/Amazon-SP-API-CSharp#474]
Getting the following error when calling GetTransportDetails.  Seems to be a serialization issue on TransportDetails.PartneredLtlData.BoxCount

Newtonsoft.Json.JsonSerializationException
  HResult=0x80131500

  Message=Error converting value 50 to type 'FikaAmazonAPI.AmazonSpApiSDK.Models.FulfillmentInbound.UnsignedIntType'. Path 'payload.TransportContent.TransportDetails.PartneredLtlData.BoxCount', line 35, position 59.
  Source=Newtonsoft.Json

Inner Exception 1:
ArgumentException: Could not cast or convert from System.Int64 to FikaAmazonAPI.AmazonSpApiSDK.Models.FulfillmentInbound.UnsignedIntType.

  StackTrace:
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ResolvePropertyAndCreatorValues(JsonObjectContract contract, JsonProperty containerProperty, JsonReader reader, Type objectType)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObjectUsingCreatorWithParameters(JsonReader reader, JsonObjectContract contract, JsonProperty containerProperty, ObjectConstructor`1 creator, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ResolvePropertyAndCreatorValues(JsonObjectContract contract, JsonProperty containerProperty, JsonReader reader, Type objectType)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObjectUsingCreatorWithParameters(JsonReader reader, JsonObjectContract contract, JsonProperty containerProperty, ObjectConstructor`1 creator, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at FikaAmazonAPI.Services.RequestService.<ExecuteRequestTry>d__38`1.MoveNext()
   at FikaAmazonAPI.Services.RequestService.<ExecuteRequestAsync>d__42`1.MoveNext()
   at FikaAmazonAPI.Services.FulFillmentInboundService.<GetTransportDetailsAsync>d__16.MoveNext()
   at FikaAmazonAPI.Services.FulFillmentInboundService.GetTransportDetails(String shipmentId)

  This exception was originally thrown at this call stack:
    [External Code]

**Comment by youst03** [comment]
This error gets fixed if the BoxCount is changed from UnsignedIntType to int.  However it exposes another bug:

Newtonsoft.Json.JsonSerializationException: 'Error converting value "IN" to type 'FikaAmazonAPI.AmazonSpApiSDK.Models.FulfillmentInbound.UnitOfMeasurement'. Path 'payload.TransportContent.TransportDetails.PartneredLtlData.PalletList[0].Dimensions.Unit', line 52, position 77.'

This can be fixed by updating the Converter for UnitOfMeasure

`    [JsonConverter(typeof(UnitOfMeasureConverter))]

    public enum UnitOfMeasurement
    {

        /// <summary>
        /// Enum Inches for value: inches
        /// </summary>
        [EnumMember(Value = "inches")]
        Inches = 1,

        /// <summary>
        /// Enum Centimeters for value: centimeters
        /// </summary>
        [EnumMember(Value = "centimeters")]
        Centimeters = 2,
    }

    class UnitOfMeasureConverter : StringEnumConverter
    {
        public override bool CanConvert(Type objectType)
        {
            return objectType == typeof(UnitOfMeasurement);
        }

        public override object ReadJson(JsonReader reader, Type objectType, object existingValue, JsonSerializer serializer)
        {
            var value = (string)reader.Value;
            switch (value.ToLower())
            {
                case "inches":
                case "in":
                    return UnitOfMeasurement.Inches;
                case "centimeters":
                case "cm":
                    return UnitOfMeasurement.Centimeters;
                default:
                    throw new ArgumentException("Invalid Unit of Measure value");
            }
        }

        public override void WriteJson(JsonWriter writer, object value, JsonSerializer serializer)
        {
            UnitOfMeasurement measure = (UnitOfMeasurement)value;
            switch (measure)
            {
                case UnitOfMeasurement.Inches:
                    writer.WriteValue("inches");
                    break;
                case UnitOfMeasurement.Centimeters:
                    writer.WriteValue("centimeters");
                    break;
            }
        }`

Similar once you get past this there is an error with the deserialization of SellerFreightClass
Newtonsoft.Json.JsonSerializationException: 'Error converting value "125.0" to type 'FikaAmazonAPI.AmazonSpApiSDK.Models.FulfillmentInbound.SellerFreightClass'. Path 'payload.TransportContent.TransportDetails.PartneredLtlData.PreviewFreightClass', line 308, position 75.'

`    [JsonConverter(typeof(SellerFreightClassConverter))]

    public enum SellerFreightClass
    {

        /// <summary>
        /// Enum _50 for value: 50
        /// </summary>
        [EnumMember(Value = "50")]
        _50 = 1,

        /// <summary>
        /// Enum _55 for value: 55
        /// </summary>
        [EnumMember(Value = "55")]
        _55 = 2,

        /// <summary>
        /// Enum _60 for value: 60
        /// </summary>
        [EnumMember(Value = "60")]
        _60 = 3,

        /// <summary>
        /// Enum _65 for value: 65
        /// </summary>
        [EnumMember(Value = "65")]
        _65 = 4,

        /// <summary>
        /// Enum _70 for value: 70
        /// </summary>
        [EnumMember(Value = "70")]
        _70 = 5,

        /// <summary>
        /// Enum _775 for value: 77.5
        /// </summary>
        [EnumMember(Value = "77.5")]
        _775 = 6,

        /// <summary>
        /// Enum _85 for value: 85
        /// </summary>
        [EnumMember(Value = "85")]
        _85 = 7,

        /// <summary>
        /// Enum _925 for value: 92.5
        /// </summary>
        [EnumMember(Value = "92.5")]
        _925 = 8,

        /// <summary>
        /// Enum _100 for value: 100
        /// </summary>
        [EnumMember(Value = "100")]
        _100 = 9,

        /// <summary>
        /// Enum _110 for value: 110
        /// </summary>
        [EnumMember(Value = "110")]
        _110 = 10,

        /// <summary>
        /// Enum _125 for value: 125
        /// </summary>
        [EnumMember(Value = "125")]
        _125 = 11,

        /// <summary>
        /// Enum _150 for value: 150
        /// </summary>
        [EnumMember(Value = "150")]
        _150 = 12,

        /// <summary>
        /// Enum _175 for value: 175
        /// </summary>
        [EnumMember(Value = "175")]
        _175 = 13,

        /// <summary>
        /// Enum _200 for value: 200
        /// </summary>
        [EnumMember(Value = "200")]
        _200 = 14,

        /// <summary>
        /// Enum _250 for value: 250
        /// </summary>
        [EnumMember(Value = "250")]
        _250 = 15,

        /// <summary>
        /// Enum _300 for value: 300
        /// </summary>
        [EnumMember(Value = "300")]
        _300 = 16,

        /// <summary>
        /// Enum _400 for value: 400
        /// </summary>
        [EnumMember(Value = "400")]
        _400 = 17,

        /// <summary>
        /// Enum _500 for value: 500
        /// </summary>
        [EnumMember(Value = "500")]
        _500 = 18
    }

    class SellerFreightClassConverter : StringEnumConverter
    {
        public override bool CanConvert(Type objectType)
        {
            return objectType == typeof(SellerFreightClass);
        }

        public override object ReadJson(JsonReader reader, Type objectType, object existingValue, JsonSerializer serializer)
        {
            var readerValue = reader.Value?.ToString();
            if (!decimal.TryParse(readerValue, out var classValue))
            {
                throw new Exception($"Unable to parse Seller Freight Class Value: {readerValue} as a decimal");
            }

            switch (classValue)
            {
                case 50:
                    return SellerFreightClass._50;
                case 55:
                    return SellerFreightClass._55;
                case 60:
                    return SellerFreightClass._60;
                case 65:
                    return SellerFreightClass._65;
                case 70:
                    return SellerFreightClass._70;
                case 77.5m:
                    return SellerFreightClass._775;
                case 85:
                    return SellerFreightClass._85;
                case 92.5m:
                    return SellerFreightClass._925;
                case 100:
                    return SellerFreightClass._100;
                case 110:
                    return SellerFreightClass._110;
                case 125:
                    return SellerFreightClass._125;
                case 150:
                    return SellerFreightClass._150;
                case 175:
                    return SellerFreightClass._175;
                case 200:
                    return SellerFreightClass._200;
                case 250:
                    return SellerFreightClass._250;
                case 300:
                    return SellerFreightClass._300;
                case 400:
                    return SellerFreightClass._400;
                case 500:
                    return SellerFreightClass._500;
                default:
                    throw new ArgumentException("Invalid SellerFreightClass value");
            }
        }


        public override void WriteJson(JsonWriter writer, object value, JsonSerializer serializer)
        {
            var enumValue = (SellerFreightClass)value;
            switch (enumValue)
            {
                case SellerFreightClass._50:
                    writer.WriteValue("50");
                    break;
                case SellerFreightClass._55:
                    writer.WriteValue("55");
                    break;
                case SellerFreightClass._60:
                    writer.WriteValue("60");
                    break;
                case SellerFreightClass._65:
                    writer.WriteValue("65");
                    break;
                case SellerFreightClass._70:
                    writer.WriteValue("70");
                    break;
                case SellerFreightClass._775:
                    writer.WriteValue("77.5");
                    break;
                case SellerFreightClass._85:
                    writer.WriteValue("85");
                    break;
                case SellerFreightClass._925:
                    writer.WriteValue("92.5");
                    break;
                case SellerFreightClass._100:
                    writer.WriteValue("100");
                    break;
                case SellerFreightClass._110:
                    writer.WriteValue("110");
                    break;
                case SellerFreightClass._125:
                    writer.WriteValue("125");
                    break;
                case SellerFreightClass._150:
                    writer.WriteValue("150");
                    break;
                case SellerFreightClass._175:
                    writer.WriteValue("175");
                    break;
                case SellerFreightClass._200:
                    writer.WriteValue("200");
                    break;
                case SellerFreightClass._250:
                    writer.WriteValue("250");
                    break;
                case SellerFreightClass._300:
                    writer.WriteValue("300");
                    break;
                case SellerFreightClass._400:
                    writer.WriteValue("400");
                    break;
                case SellerFreightClass._500:
                    writer.WriteValue("500");
                    break;
                default:
                    throw new ArgumentException("Invalid SellerFreightClass value");
            }
        }`


Also get the error:
Newtonsoft.Json.JsonSerializationException: 'Error converting value 1/19/2023 2:14:47 PM to type 'FikaAmazonAPI.AmazonSpApiSDK.Models.FulfillmentInbound.TimeStampStringType'. Path 'payload.TransportContent.TransportDetails.PartneredLtlData.PartneredEstimate.ConfirmDeadline', line 321, position 94.'

I think ConfirmDeadline and VoidDeadline should just be strings.

**Comment by abuzuhri** [comment]
Please share code you use will try to regenerate the error

**Comment by youst03** [comment]
`
var amazonResult = SPAPIConnection.Instance.Connection.FulFillmentInbound.EstimateTransport(shipmentId);


                var status = TransportStatus.ESTIMATING;
                var transportDetailsResult = new GetTransportDetailsResult();
                while (status == TransportStatus.ESTIMATING)
                {
                    Thread.Sleep(1000);
                    transportDetailsResult = SPAPIConnection.Instance.Connection.FulFillmentInbound.GetTransportDetails(shipmentId);
                    status = transportDetailsResult.TransportContent.TransportResult.TransportStatus;
                }
`

It breaks on the following line: transportDetailsResult = SPAPIConnection.Instance.Connection.FulFillmentInbound.GetTransportDetails(shipmentId);
