### ISSUE TITLE
System.ArgumentException: Requested value 'JE_VOEC' was not found.

### ISSUE THREAD

**Issue by owenashurst** [abuzuhri/Amazon-SP-API-CSharp#640]
I've noticed over the past couple weeks I keep getting the same error when retrieving Order Items for Amazon Orders.

```csharp
011423f9-3d6c-4b6e-9338-456f8c4ca465	fail	Newtonsoft.Json.JsonSerializationException: Error converting value "JE_VOEC" to type 'System.Nullable`1[FikaAmazonAPI.AmazonSpApiSDK.Models.Orders.OrderItem+DeemedResellerCategoryEnum]'. Path 'payload.OrderItems[0].DeemedResellerCategory', line 1, position 762.

System.ArgumentException: Requested value 'JE_VOEC' was not found.
at Newtonsoft.Json.Utilities.EnumUtils.ParseEnum(Type enumType, NamingStrategy namingStrategy, String value, Boolean disallowNumber)
at Newtonsoft.Json.Converters.StringEnumConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
```

I'm running this using .NET 6 in an AWS Lambda Function.

This is halting one of my clients abilities to add orders into their system.

**Comment by abuzuhri** [comment]
this added alredy from some times , which version you are using ?

**Comment by swisst182** [comment]
Fixed, I didn't realize a newer version had the fix for this. Updating to the latest version fixed my issue.
