### ISSUE TITLE
getting error "Amazon Api didn't respond with Okay"

### ISSUE THREAD

**Issue by abhishek0256** [abuzuhri/Amazon-SP-API-CSharp#94]
Hi abuzuhri,

Your code work good and thanks for sharing code.

while retrieving the order details i am getting following error message :-  "Amazon Api didn't respond with Okay, see exception for more details"

kindly suggest.

**Comment by abuzuhri** [comment]
Hello @abhishek0256 

Can you give more details with stacks trace?

**Comment by abhishek0256** [comment]
at FikaAmazonAPI.AmazonSpApiSDK.Runtime.LWAClient.GetAccessToken()
   at FikaAmazonAPI.Services.TokenGeneration.RefreshAccessToken(AmazonCredential credentials, TokenDataType tokenDataType)
   at FikaAmazonAPI.Services.RequestService.RefreshToken(TokenDataType tokenDataType, CreateRestrictedDataTokenRequest requestPII)
   at FikaAmazonAPI.Services.RequestService.CreateAuthorizedRequest(String url, Method method, List`1 queryParameters, Object postJsonObj, TokenDataType tokenDataType, Object parameter)
   at FikaAmazonAPI.Services.ReportService.GetReports(ParameterReportList parameterReportList)

**Comment by abuzuhri** [comment]
Which version you are Using

**Comment by abhishek0256** [comment]
mvc or what ?

**Comment by abuzuhri** [comment]
Please contact me my email i need to know more information to try to fix this problem

**Comment by abuzuhri** [comment]
After internal checking there is no problem and I will close this case .

please let me know if you need more help
